### PR TITLE
Change editorConfig and excute it

### PR DESCRIPTION
**Pull request by soi013**
Retry  #1688

Excute editorConfig.

dotnet-format.exe -w

I did NOT change .editorconfig.

### CODE REVIEW

**Comment by jespersh** [comment]
Are we missing something to editorconfig since it is placing { on the same line for initializers?
```diff
---            var metroDialogSettings = new MetroDialogSettings
---            {
+++            var metroDialogSettings = new MetroDialogSettings {
```

**Comment by soi013** [comment]
It's depdend on `csharp_new_line_before_open_brace` in `.editorconfig`.

Should I change it?

```
csharp_new_line_before_open_brace = methods, accessors, anonymous_methods, types, properties, control_blocks, lambdas, indexers

or

csharp_new_line_before_open_brace =all
```

In my opinion, `all` is better.

**Comment by Keboo** [comment]
I would say `all` is preferable

**Comment by jespersh** [comment]
Nice.

**Pull request merged**
