### PR TITLE
New Scrollbar Style

### LINKED ISSUE #646: Android-like scrollbar style
It would be nice to have a style for scrollbar that mimics how it usually looks on mobile devices - hidden until you start scrolling, doesn't take up space, is overlayed on top of content.

A lot of desktop and web apps also use some variation of that style. For example, here is how it looks on Twitch.tv (the scrollbar is the greyish round rectangle on the right).

2017-03-04 19_37_27-lirik - twitch

### PR DESCRIPTION
**Pull request by AlbertAlonso**
FIXES #646 

I've added a different style to the scrollbar following the requests of #646. 

This PR introduces:

1. ScrollBarAssist: Allows to change the visibility of the arrows with `ScrollBarAssist.ArrowsVisibility="Collapsed"`
2. Styles **MaterialDesignScrollBarStyle** and **MaterialDesignMinimalScrollBar**, the latter has the arrows hidden. Both cases are for Vertical and Horitzontal ScrollBars.
3. Added the style to the Navigation Drawer in the Demo App (Only place I've seen with scrollbar).
Since MaterialDesignScrollBar is taken, I've added Style at the tail to avoid conflicts. 

MaterialDesignScrollBar
normal_scrollbar

MaterialDesignMinimalScrollBar
minimal_scrollbar

The Thumb corner radius is set to 6, but feel free to change it if you don't like it.  

**UPDATE:** 
Ok, so I just saw PR #651.  Totally missed it. You can discard this PR if that one already fixes the Issue. As you please.

### CODE REVIEW

**Comment by Keboo** [comment]
@AlbertAlonso this is looking really good. I am going to review it later tonight on the [live stream](https://www.twitch.tv/events/oDhU91qcQCOJdXKJ09k_pA) and should get it merged into

**Comment by ChrisStayte** [comment]
Does this work on a scroll viewer?

**Comment by a73013110** [comment]
@ChrisStayte Yes, I try it on myself project.
The code is like this
<ScrollViewer>
    <ScrollViewer.Resources>
                <Style TargetType="ScrollBar" BasedOn="{StaticResource MaterialDesignScrollBarMinimal}" />
    </ScrollViewer.Resources>
<ScrollViewer/>

**Comment by luciano-work** [comment]
Please, how to set MaterialDesignScrollBarMinimal as Default ?

**Comment by AlbertAlonso** [comment]
@luciano-work  just add this line to the App.xaml file inside the `<ResourceDictionary>`

```
<Style BasedOn="{StaticResource MaterialDesignScrollBarMinimal}" TargetType="{x:Type ScrollBar}" />
```

Cheers.

**Comment by luciano-work** [comment]
Why horizontal scrollbar dont apply the style?
image

**Comment by pialin** [comment]
> Why horizontal scrollbar dont apply the style?
> image

I'm facing exactly same problem as @luciano-work. I think horizontal bar does apply the style, however the width was not set as expected. @AlbertAlonso, could you do us a favor?

**Comment by AlbertAlonso** [comment]
@pialin @luciano-work  I cannot test it, but from what I gather reading the code, the Height for the bar is obtained from `SystemParameters.HorizontalScrollBarHeightKey`. 

Maybe setting them as the same size in **App.xaml**
```
<Application
xmlns:sys="clr-namespace:System;assembly=mscorlib"
... >
<Application.Resources>
    <sys:Double x:Key="{x:Static SystemParameters.VerticalScrollBarWidthKey}">50</sys:Double>
    <sys:Double x:Key="{x:Static SystemParameters.HorizontalScrollBarHeightKey}">50</sys:Double>
</Application.Resources>
</Application>
```
fixes the issue. Otherwise, I'd have to take a closer look, but since I am not running Windows anymore, I can not test the possible solutions. Sorry. 

Cheers,

**Comment by luciano-work** [comment]
@AlbertAlonso Thanks ;)

**Comment by pialin** [comment]
@AlbertAlonso @luciano-work I found that if I comment `ThumbWidth` property of scrollbar style as below，i got same-width vertical and horizontal bars.  And then I can set scrollbar width I want through `SystemParameters.Vertical/Horizontal ScrollBarWidthKey` .  It is not the best solution but it works.  Thanks @AlbertAlonso  very much for your reply, it helps a lot!

            <Style x:Key="MaterialDesignScrollBarMinimal"
                   TargetType="{x:Type ScrollBar}"
                   BasedOn="{StaticResource MaterialDesignScrollBar}">
                <Setter Property="materialDesign:ScrollBarAssist.ThumbCornerRadius"
                        Value="5" />
                <Setter Property="materialDesign:ScrollBarAssist.ButtonsVisibility"
                        Value="Collapsed" />
  
                
            </Style>

**Pull request merged**
