### PR TITLE
Specified colors for themes

### PR DESCRIPTION
**Pull request by Sergey-Terekhin**
Added theme colors keys - for example, I had to theme AvalonDock control and the easiest way was to override existing brushes with Material colors, not to use existing brushes

### CODE REVIEW

**Comment by mgnslndh** [comment]
@Sergey-Terekhin Did you make a material theme for AvalonDock? If so, are you going to release it?

**Comment by Sergey-Terekhin** [comment]
@mgnslndh I can release it, but I'm only replaced colors with Material palette and icons are taken from that package not more -no animations, transitions etc

**Comment by ButchersBoy** [comment]
This PR seems to break the appearance of cards, shadows are gone:

image

**Comment by jigneshBadrakhiya** [comment]
any way to create a new color scheme from code?

**Comment by Keboo** [comment]
Moving this into 2.6.0 as there will be quite a few changes going in around colors and theming.

**Comment by Keboo** [comment]
Superseded by #1296

**Pull request closed without merging**
