### PR TITLE
Wrapped borders within AdornerDecorator

### LINKED ISSUE #1829: Refresh issue with TextBox/ListBox in ToolBar contained in TabablzControl
This is a fairly recent issue but I can't put my finger on the date of introduction.  Definitely last few months.
Check the video examples.
Identical XAML with only difference being `TabablzControl` vs. `TabControl`.
As you can see, when using `TabablzControl`, the disabled dotted line indicators are carried over to all other tabs as ghosts.

`TabablzControl`
[https://drive.google.com/open?id=1qiYnyS5QvI-OMiawksc7QUCo4LGmsu75](https://drive.google.com/open?id=1qiYnyS5QvI-OMiawksc7QUCo4LGmsu75)
Notice all good at 0:10 and ghosts starting to stick at 0:18

`TabControl`
[https://drive.google.com/open?id=1bBmn-pNd-mniw3J_aBML92I_6Npd3uuE](https://drive.google.com/open?id=1bBmn-pNd-mniw3J_aBML92I_6Npd3uuE)
Notice no ghosting issue at all **_but_** at 0:07 dotted lines vs. 0:15 they are gone and never seen again.  This is easily reproduced in Demo app by adding `TabControl` with
`
<TextBox materialDesign:HintAssist.Hint="Num Packets" IsEnabled="False" Text="1200" Margin="10,0,10,0" Width="90" Style="{StaticResource MaterialDesignFloatingHintTextBox}"/>
`
in one of the tabs.

### LINKED ISSUE #1840: Dialog host is transparent!
The dialoghost became transparent in version 3.1.2. Can you look into this please.
NB : actually this behavior is present when ever there is an overlay like an open drawer, dialoghost...

This is what I'm supposed to have (3.1.1)
Screenshot (26)

This is what it becomes in 3.1.2
Screenshot (28)

### PR DESCRIPTION
**Pull request by yosefmah**
Attempt to fix #1840 and fix #1829

### CODE REVIEW

**Comment by Keboo** [comment]
Great work. Thank you.

**Comment by greuelpirat** [comment]
I must apologize because I introduced this BottomDashedLineAdorner. I did not know this AdornerDecorator and I did not see these problems. 

Sorry for that and thank you for this fix!

**Comment by ChrisCross67** [comment]
It's works with a classic TextBox & Combox but with a Validation it does not work. 

KtdjHwWCYa

**Comment by yosefmah** [comment]
Hi @ChrisCross67 Would you be able to post a sample app or your XAML?  I couldn't seem to replicate that, but I  assume wrapping the AdornerDecorator around the whole ControlTemplate would fix it.

**Comment by ChrisCross67** [comment]
Of course, here's the sample code:

```

<materialDesign:Transitioner SelectedIndex="0">
        <StackPanel HorizontalAlignment="Center">
            <TextBlock Text="First slide" />
            <TextBox materialDesign:HintAssist.HelperText="Helper text longer than error" materialDesign:HintAssist.Hint="Name">
                <TextBox.Text>
                    <Binding Path="Name" UpdateSourceTrigger="PropertyChanged">
                        <Binding.ValidationRules>
                            <domain1:NotEmptyValidationRule ValidatesOnTargetUpdated="True" />
                        </Binding.ValidationRules>
                    </Binding>
                </TextBox.Text>
            </TextBox>

            <Button Command="{x:Static materialDesign:Transitioner.MoveNextCommand}"
                    Style="{DynamicResource MaterialDesignFloatingActionButton}">
                <materialDesign:PackIcon Kind="ArrowRight" />
            </Button>
        </StackPanel>
        <StackPanel HorizontalAlignment="Center">
            <TextBlock Text="Second slide" />
            <Button Command="{x:Static materialDesign:Transitioner.MovePreviousCommand}"
                    Style="{DynamicResource MaterialDesignFloatingActionButton}">
                <materialDesign:PackIcon Kind="ArrowLeft" />
            </Button>
        </StackPanel>
    </materialDesign:Transitioner>
```

Like you said, wrapping the TextBox with an Adorner Solved the problem.
Thanks !

**Pull request merged**
