### PR TITLE
Text fields major revision

### PR DESCRIPTION
**Pull request by greuelpirat**
Started with adjusting fields height (see #1945) it ended in a pretty big refactoring. It is still in progress, but want to share it for feedback.

fields

### CODE REVIEW

**Comment by jespersh** [comment]
This is great!

**Comment by Keboo** [comment]
This is looking really good @greuelpirat

**Comment by greuelpirat** [comment]
PR is ready:

* Reworked TextBox, PasswordBox, ComboBox, DatePicker and TimePicker
* All five controls have identical default height and resizes equals with font size and padding in all 
* Added UI-Tests for equal default height
* Floating-Hint-Offset is calculated based on font size
* Added Filled and Outlined-Style for TimePicker
* Padding can be changed within each style (Added ScrollViewerAssist.IgnorePadding to ignore Padding in ScrollViewer)
* TextViewAssist.TextBoxViewMargin works for all controls in same way

**Review by Keboo — APPROVED** [review]
This is really great work. Thank you!

**Pull request merged**
