### PR TITLE
Update MaterialDesignTheme.PasswordBox.xaml

### PR DESCRIPTION
**Pull request by DevanshCodes**
fixes issue #2074

### CODE REVIEW

**Comment by Keboo** [comment]
@DevanshCodes thank you. It looks like there is still a reference to the old style name in the demo app [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/bcd02352e9b12a51a5d927ce1228f99f6d51aeae/MainDemo.Wpf/Fields.xaml#L204) that should be updated as well.

**Comment by DevanshCodes** [comment]
Yeah sorry, later realised that xD. I'll look into it ASAP

**Comment by DevanshCodes** [comment]
Fixed it. Please take a look. :)

**Comment by DevanshCodes** [comment]
hey @Keboo is it fine?

**Comment by Keboo** [comment]
@DevanshCodes thanks, looks good. 
@AmRo045 I will review the other styles and see about naming

**Pull request merged**
