### PR TITLE
Added Optimizing-WPF-Rendering-Performance.md file to docd

### PR DESCRIPTION
**Pull request by ArshadAriff**
Added Optimizing-WPF-Rendering-Performance.md file to docd

### CODE REVIEW

**Comment by ArshadAriff** [comment]
Sir please do tell me if any changes are to be made.!

**Comment by ArshadAriff** [comment]
Sir does this count to my Hacktoberfest PRs?

**Comment by ArshadAriff** [comment]
@Keboo !

**Review by Keboo — APPROVED** [review]

**Comment by ArshadAriff** [comment]
@Keboo can you attach hacktober fest acceptance label?

**Pull request merged**
