### PR TITLE
Excute editorConfig

### PR DESCRIPTION
**Pull request by soi013**
Excute editorConfig.

```
dotnet-format.exe -w
```

I did NOT change `.editorconfig`.

### CODE REVIEW

**Comment by soi013** [comment]
#1009

**Comment by soi013** [comment]
Umm...
I did not change `PackIconDataFactory.cs`. However it changed.
What`s going on?

**Comment by Keboo** [comment]
@soi013 hat file is auto generated o a nightly basis. I suspect this just need to be rebased on latest.

**Comment by soi013** [comment]
I think this PR is too messiness.
I will recreate.

**Pull request closed without merging**
