### PR TITLE
Properly restore focus when TabControl.SelectedIndex is set via DialogHost

### LINKED ISSUE #3094: TabControl.SelectedIndex via DialogHost (repo)
### Bug Description
When opening a dialog `await DialogHost.Show(view);` via **MenuItem** (System.Windows.Controls) and setting the `SelectedIndex` of a TabControl by e.g. clicking a button, the selected tab is still the _old_ one after the dialog has been closed.
The property that holds the `SelectedIndex` receives the new value but instantly switches back to the previous index, which can result in a _flicker_.

### Reproduction
In order to reproduce the bug, please select the **second tab** (**Info**). Then click on **Menu** in the top right corner. Select **Settings** and click on the button in the dialog.

### Debugging
I have found out that it does make a difference whether the dialog is opened via said **MenuItem**, a **PopupBox** (Material Design) or a button on any **view**:
It does work es expected in both of the last two cases, just the MenuItem-way fails.
In order to make it work, insert `await Task.Delay(500);` (at least 200-300) before setting `SelectedIndex` to its new value. I'm not a fan of using `Task.Delay()` but currently out of ideas how to make it work without it.

Using DI does not make a difference in any of the above mentioned behaviors.

### Installed NuGet packages:
- CommunityToolkit.Mvvm (8.1.0)
- MaterialDesignThemes (4.7.1)
- Microsoft.Extensions.DependencyInjection (7.0.0)
- Microsoft.Extensions.Hosting (7.0.1)

### Link
[GitHub Repository](https://github.com/VR462002/MDIX-DialogHost-TabControl)

### Version

4.7.1 (latest stable)

### PR DESCRIPTION
**Pull request by nicolaihenriksen**
Fixes #3094

As per the discussion thread below, this PR adds `DialogHost.RestoreFocusElement` and `DialogHost.IsRestoreFocusDisabled` attached/dependency properties.

The former is currently used for the `TabItem` style (also the one for the "rail item") to ensure focus is returned to the parent `TabControl` rather than the `TabItem` itself.

The latter is used to completely disable the restore focus feature in case that is relevant.

Added 4 UI tests to verify the behavior.

### CODE REVIEW

**Comment by Keboo** [comment]
After giving it some thought here would be my proposal.

1. Create a new `DialogHost.RestoreFocusElement` (perhaps with a better name)
2. When setting `DialogHost._restoreFocusDialogClose` first check that element to see if the above attached property has a value, if it does use it for the `_restoreFocusDialogClose` value.
3. In the style for the TabItem (`MaterialDesignTabItem`) we do a relative binding looking for a parent tab control (something like: `{Binding RelativeSource={RelativeSource FindAncestor, AncestorType=TabControl}}`). We may need to look at other styles as well, such as `MaterialDesignNavigationRailTabItem`.
4. Optionally, we could consider a mechanism for turning off the restore focus behavior (I say optional because rarely has anyone ever requested this). But we could create a static property on DialogHost (something like `DialogHost.DisableRestoreFocus` or a better name). Then in step 2 above if that is the value of the attached property, we would set `DialogHost._restoreFocusDialogClose` to null to effectively disable the behavior.

Thoughts?

**Comment by nicolaihenriksen** [comment]
> After giving it some thought here would be my proposal.
> ...
> Thoughts?

I think this sound like a very good approach. I very much like the idea that the responsibility for picking the correct element to focus is removed from the `DialogHost` and put into the respective controls themselves. This aligns nicely with the Tell Don't Ask principle. Also, it is probably a rather limited number of controls which face this type of (possible) issue.

Having the additional option to completely disable the restore behavior also seems like a good idea to me. We'll just default the property to `false` such that it is something a caller would have to explicitly request for the `DialogHost`.

Writing UI tests to ensure this behavior works may or may not prove to be a non-trivial task. I'll spend a little time to see if I can write a (failing) UI test for the scenario included in the sample repro project included in this branch.

**Comment by Keboo** [comment]
This is great. I think there is a bit of a disjoint on the names of the properties. (FocusRestore vs RestoreFocus). I think `IsFocusRestoreDisabled` should probably be the one changed to `IsRestoreFocusDisabled`. Thoughts?

**Comment by nicolaihenriksen** [comment]
> This is great. I think there is a bit of a disjoint on the names of the properties. (FocusRestore vs RestoreFocus). I think `IsFocusRestoreDisabled` should probably be the one changed to `IsRestoreFocusDisabled`. Thoughts?

I agree, I'll change it.

**Comment by VR462002** [comment]
Hi Nicolai and Kevin,

thank you for working on this, you guys are awesome!

@nicolaihenriksen Thanks for testing and explaining the focus problem!
@Keboo Always appreciate your input and enjoy your live videos/recordings

**Review by Keboo — APPROVED** [review]

**Pull request merged**
