### PR TITLE
Updating ShowMeTheXaml to 1.0.10

### LINKED ISSUE #929: The "BuildXamlDictionaryTask" task failed unexpectedly.
Trying to run the demo app and i keep getting this error

The "BuildXamlDictionaryTask" task failed unexpectedly. 
System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0		

materialdesignerror

Please i need help!

### PR DESCRIPTION
**Pull request by Keboo**
Fixes #929

### CODE REVIEW

**Comment by ahmedflix25** [comment]
there is no scrollbar in the controller and i can't see the long codes like this one https://imgur.com/02qpbu0

**Comment by Keboo** [comment]
@ahmedflix25 I believe that issue is the same as #885 and should be fixed by PR #887

**Comment by ahmedflix25** [comment]
@Keboo that it, thanks

**Comment by ahmedflix25** [comment]
it works as expected but there is that small thing when the length of the code is bigger than the popup width in a line, the popup width will increase -if there is enough space- and/or the horizontal scrollbar will show up -if there isn't enough space- 
continue scrolling to a normal length line and the popup will restore its width again and the horizontal scrollbar will collapse it's not a problem but it's annoying https://imgur.com/a/RsDEPPC

**Comment by Keboo** [comment]
@ahmedflix25 agreed. That behavior is actually coming from the Avalon control that is being used to get the nice syntax highlighting. I suspect it is due to the virtualization that is used (making work well for large blocks of text). I have not looked into options for addressing that yet.

**Pull request merged**
