### PR TITLE
Added IsReadOnly Property to RatingBar

### PR DESCRIPTION
**Pull request by Insire**
Added IsReadOnly Property to RatingBar, which disables updating the Value-Property of the RatingBar, when any of the child RatingBarButtons is clicked. The OnClick spinning animation is disabled by this aswell.

#670

### CODE REVIEW

**Comment by Insire** [comment]
I'm sorry about the extra changes, i have an extension that removes them for me when saving documents. Is this still acceptable?

**Comment by ButchersBoy** [comment]
Hey...can't we just use existing IsEnabled property (and stop it greying out)?

**Comment by Insire** [comment]
Sure, thats an option. The tradeoff is predictability of the default behavior vs more code.

I prefer the more code approach, so that its easier to use for the dev using the ratingbar, but if you like the to use the IsEnabled property instead, i can do that.

**Comment by Keboo** [comment]
@Insire are you able to address the merge conflicts?

**Comment by Insire** [comment]
Pulled and rebased onto master.

Also added a sample for a readonly ratingbar to the demo app.

**Pull request merged**
