### PR TITLE
DialogHost and VisualTree

### PR DESCRIPTION
**Pull request by Streissi**
This PR fixes two issues:

1. The fadeout background animation from the dialoghost #1022 
2. the visual tree in studio #1005 

dialoganimation
visualtree

### CODE REVIEW

**Comment by jespersh** [comment]
@equimal pull #905
@cjvaughter pull #772 
Looks good to you two?

**Comment by cjvaughter** [comment]
👍

**Comment by jizc** [comment]
You might as well also remove lines [189](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/d6a451c1800ad000306033c85224a63af47142cd/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml#L189) and [363](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/d6a451c1800ad000306033c85224a63af47142cd/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml#L363), now that the background brush is always Black. 

Otherwise great job! 😃

**Comment by cjvaughter** [comment]
Aha! I didn't think about that. Good catch.

**Comment by Keboo** [comment]
@Streissi really good work. Two issues I noticed.

1. The `MaterialDesignEmbeddedDialogHost` got its `PART_ContentCoverGrid`'s background set to `Black` but did not get the same updates for the visual state changes. This causes it to always show black (Sample 5 on the Dialogs pages in the sample app).
2. The `DrawerHost` removes its `PART_ContentCover` grid when you close _any_ drawer. It should leave it visible and only hide it when the last drawer is closed. You can see this in the sample app if you go to the drawer host demo, open all of the drawers and then close them one at a time.

**Comment by Streissi** [comment]
@Keboo @jizc thanks for the feedback i will fix that

**Comment by Keboo** [comment]
@Streissi could you take a look at the latest stuff on master (or NuGet 2.5.0-ci1202). I think the issues referenced here are fixed.

**Comment by Keboo** [comment]
Closing for now, if there is anything from this that does not exist in the current master branch please let me know.

**Pull request closed without merging**
