### PR TITLE
Password field box #973

### PR DESCRIPTION
**Pull request by Streissi**
- added a style for a PasswordFieldBox for Issue #973 
passwordfieldbox

### CODE REVIEW

**Comment by Keboo** [comment]
Very nice work.

**Comment by almas3s** [comment]
thanks for this!
but why **MaterialDesignPasswordFieldBoxPasswordBox** not available in version 2.5.0 ?
@Keboo @Streissi

**Comment by Keboo** [comment]
@almas3s it will be. But this has not been merged yet. There are merge conflicts that need to be addressed first, and I have been trying to test PRs before merging them as well.

**Comment by Streissi** [comment]
Ohh i did not saw the merge conflict. I take a look in it. For the future @Keboo is it possible to get a notification on merge conflicts?

**Comment by Keboo** [comment]
@Streissi I don't think so. Mostly because the conflict likely just occured as the result of me merging in other PRs. The conflicts are not a huge deal, since I can also resolve them before merging.

**Comment by Keboo** [comment]
Really nice work!

**Pull request merged**
