### PR TITLE
Added MaterialDesignChoiceChip(Outline)RadioButton

### PR DESCRIPTION
**Pull request by JorisCleVR**
- Added choice chip radio buttons and their list box variants
- Filter chips added color styles (to have similar styling options as ChoiceChips)
- Fixed issue with ChoiceChip outline not having an outline when selected
Open issue: color styles not always readable in dark mode

### CODE REVIEW

**Comment by Keboo** [comment]
I rebased it and added in a check to flip the foreground and background colors. Unfortunately it looks like I don't have push permission back into the branch, so I push it here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/feature/MaterialDesignChoiceChipListBox

**Comment by Keboo** [comment]
Still want to look a little more into it, but it looking very promising.

**Comment by JorisCleVR** [comment]
Nice work. The attached property seems to do the job :). I have rebased it back into the branch and also applied it to the CheckBoxes.

**Comment by Keboo** [comment]
That for the last update. It looks like your rebase picked up an extra merge commit. I did get these changes merged in here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1847

**Pull request closed without merging**
