### PR TITLE
Change Calendar TodayBackground to Transparent with a circle around it

### PR DESCRIPTION
**Pull request by ahmedflix25**
Calendar Today Background color and Selected Background color have very similar color and it's confusing for some now the Today Background Color has accent brush color

### CODE REVIEW

**Comment by jizc** [comment]
I agree that the current style is not ideal. But I think a better solution would be to changed it to the current spec of an ellipse with a foreground brush stroke (1 thickness). You can see it in the first image here: https://material.io/components/pickers/

**Comment by ahmedflix25** [comment]
image

**Comment by jizc** [comment]
Using `Black` as the `Stroke` is going to be an issue when using the dark theme. I would suggest using `{TemplateBinding Foreground}` instead.

**Comment by ahmedflix25** [comment]
the number inside the circle for current date will always be black and i can't figure out what makes it behave like that

**Comment by jizc** [comment]
The black text on Today is caused by the `ObjectAnimationUsingKeyFrames` on line [218](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/aa293c74a30b134a0d48151879bf2fc3a39d7d40/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml#L218). It is no longer needed, as the background of the Today indicator is no longer filled. Removing it solves the problem.

**Comment by ahmedflix25** [comment]
i think we did it thanks for the help @jizc

**Comment by jizc** [comment]
Happy to help! You might want to change the title of the PR to reflect your latest changes.

**Comment by Keboo** [comment]
Very nice work. And thank you to @jizc for the code reviews.

**Pull request merged**
