### PR TITLE
Close dialog when window is hidden.

### LINKED ISSUE #644: DialogHost freezing
[**Source**](https://github.com/Carlj28/MaterialDesignDialogHostFreezing)

Steps to reproduce:
1. Click "Open sub window"
2. Click "Open DH"
3. Close "Sub window" (close is overriden, it actualy hides)
```
        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            this.Hide();
            e.Cancel = true;
        }
```
4. DialogHost is still open after closing (hiding) parent window

5. Click "Open sub window"
6. Click "Open DH" and DialogHost is now frozen

This occurs when parent window of DialogHost is Hidden instead of closing.

### PR DESCRIPTION
**Pull request by Keboo**
Fixes #644 

When the parent window is hidden, the DialogHost closes its popup.

### CODE REVIEW

**Comment by ButchersBoy** [comment]
I'm wondering if we should hide the popup (temporarily) and not close it.  Because 1) the dialog could stuill be valid if a window is re-shown, and 2) if we start calling ``` Close{null) ``` then there maybe unwanted effects in user code where people may coded for specific return parameters.

We actually have a ``` CloseOnClickAwayParameter ``` for similar circimstances...but I'm wondering if adding a switch is just going to complicate the API...

Thoughts?

**Comment by Keboo** [comment]
This actually touches on something I have been thinking about. Have you ever considered changing out the DialogHost to simply be a content control, rather than utilizing the popup (similar to the way MahApps does their dialogs)? It just seems like this approach would be much simpler to manage as the dialog would then behave the way it looks (as an element within the visual tree; rather than a light weight window outside of it).

As for this particular issue. What about a flagged enum (perhaps obsolete the existing CloseOnClickAway)?

```C#
[Flags]
public enum DialogCloseEvents
{
    None = 0,
    ClickAway = 1,
    ParentWindowHidden = 2
}

```

**Comment by ButchersBoy** [comment]
Yes, I did consider this in the beginning, and decided against it.  The problem with that is it's size is constrained to the parent Window.

**Comment by Keboo** [comment]
Fair enough. In my own applications, I actually want the size constrained to the parent window so I am just using relative bindings on MaxWidth/MaxHeight to enforce it.

**Comment by Keboo** [comment]
@ButchersBoy see the updated changes. I did both the flagged enum and well as only hiding/showing the dialog when the parent window is hidden/shown. 
I am happy to change this up more, if this is not in line with what you were thinking.

**Comment by ButchersBoy** [comment]
I would prefer we take a step back a little and simplify this.

The underlying UX issue is that we just need to hide the dialog whilst a window is minimized (right?).

So the extra "trigger" is unnecessary.  Once a window is restored, the dialog should still be there.  The user hasn't dismissed it and and the code hasn't called a .Session.Close().

Plus I'd rather avoid obsoleting stuff unless necessary.

**Comment by Keboo** [comment]
@ButchersBoy more like this?

**Comment by Keboo** [comment]
Closing this for now. After reviewing my solution I don't believe it is the best possible option. A better solution is to use the embedded dialog host style instead.

**Pull request closed without merging**
