### PR TITLE
Fix: #1097 & #1198 Adding a UseLayoutRounding=True to the DialogHost 

### PR DESCRIPTION
**Pull request by Tokter**
seems to fix the issue reported in #1097 & #1198

### CODE REVIEW

**Comment by Keboo** [comment]
Should this also get applied to the `MaterialDesignEmbeddedDialogHost` below?

**Comment by jespersh** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.uselayoutrounding?view=netframework-4.7.2#remarks
> You should set UseLayoutRounding to true on the root element. The layout system adds child coordinates to the parent coordinates; therefore, if the parent coordinates are not on a pixel boundary, the child coordinates are also not on a pixel boundary. If UseLayoutRounding cannot be set at the root, set SnapsToDevicePixels on the child to obtain the effect that you want. 

Is DialogHost the root element? I forgot if it is.

**Comment by Tokter** [comment]
@Keboo Yes, I added it as well.
@jespersh Not sure, but it creates a popup with its own Visual Tree, so I think so...

**Comment by Keboo** [comment]
@jespersh that is an excellent point. _Usually_ the dialog host is a root level element inside of the window but it doesn't have to be (the demo app [shows this case](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Dialogs.xaml)). 
By setting this on the DialogHost element directly it will propagate down to both the dialog itself as well as all of the control that are being wrapped by the DialogHost. Given that, and the suggestion from the docs about wanting to set this on the root element to handle the case where a nested element may not be on the pixel boundary, I think I would suggest the following (assuming I am understanding everything correctly):
1. Set UseLayoutRounding on [MaterialDesignDialogHostPopup](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml#L9-L14). That way it will get applied to the Popup control (and I suspect resolve your issue as well). 
2. Avoid setting it on the DialogHost since there are no guarantee that it will exist on the pixel boundaries. If people know that it is what they want, based on how they are using the DialogHost in their app, they are free to derive from the MDIX style and add it.
3. We should be able to ignore the embedded dialog host (sorry for my previous comment) since it lives in the same visual tree.

**Comment by Tokter** [comment]
@Keboo Your suggestion in point 1 works, UseLayoutRounding appear on the root element:
image

But the embedded dialog is then still glitchy:
image

image

image

**Comment by Tokter** [comment]
I guess you could say that if you use the embedded dialog, then its up to the user to add a UseLayoutRounding on the MainWindow.

**Comment by Keboo** [comment]
@Tokter yea I think simply documenting that behavior for the embedded dialog host is the way to go. I have been working on trying to update the wiki with lots of this knowledge.

**Comment by Keboo** [comment]
Wiki documentation added [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs#dialog-content-shows-border-lines)

**Pull request closed without merging**
