### PR TITLE
Uniform style in demo app pages

### PR DESCRIPTION
**Pull request by MichelMichels**
I'm reviewing the demo app pages to create a more uniform style and fixing some minor style issues.

Pages: 
- [X] Buttons
- [X] Cards
- [X] Chips
- [X] Color Tool
- [X] Colour Zones
- [X] ComboBoxes
- [X] Data Grids
- [x] Dialogs
- [x] Drawer
- [x] Elevation
- [x] Expander
- [x] Fields
- [x] Fields line up
- [x] Group Boxes
- [x] Icon Pack
- [x] Lists
- [x] Menus & Tool Bars
- [x] Navigation Rail
- [x] Palette
- [x] Pickers
- [x] Progress Indicators
- [x] Rating Bar
- [x] Sliders
- [x] Snackbar
- [x] Tabs
- [x] Toggles
- [x] Transitions
- [x] Trees
- [x] Typography

Other:
- [X] Documentation links in header `VerticalAlignment = Center` for `TextBlock`

### CODE REVIEW

**Comment by Xaalek** [comment]
I thought the wrapping issue was fixed but it's not.
I haven't checked all views but I can say that Card and Elevation view are not wrapped compared to the old versions
See: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/2862
It would be nice to fix that

**Comment by MichelMichels** [comment]
@Xaalek could you clarify what behavior is desired? Do you mean WrapPanel style wrapping?

Atm the Cards page gets a horizontal and vertical scrollbar when the windows size is too small for the content (see screenshot below).
image

**Comment by MichelMichels** [comment]
@Xaalek The issue is in MaterialDesignDemo.Domain.DemoItem.
```csharp
private ScrollBarVisibility _horizontalScrollBarVisibilityRequirement = ScrollBarVisibility.Auto;
private ScrollBarVisibility _verticalScrollBarVisibilityRequirement = ScrollBarVisibility.Auto;
```

The default horizontalscrollbarvisibility should be ScrollBarVisibility.Disabled in my opinion.
When I set it manually on the demoitem for the cards page, this works as intended.

@Keboo can I change this default value? Horizontal scrolling for a desktop app doesn't seem intuitive to me, but maybe this is a personal preference.

**Comment by Xaalek** [comment]
In the old versions of the demo, views was wrapped
Old (4.5.0):
image
New (last):
image

**Comment by MichelMichels** [comment]
> In the old versions of the demo, views was wrapped Old (4.5.0): (...)

@Xaalek I fixed it in one of the previous commits.

**Comment by Keboo** [comment]
@MichelMichels yes feel free to change the default.

**Comment by MichelMichels** [comment]
> @MichelMichels yes feel free to change the default.

Thanks! But in the meantime I found out that it's better to leave it this way and change it on specific pages where it's needed.

**Comment by MichelMichels** [comment]
Better late than never I guess. Ready for merging with master!

**Comment by MichelMichels** [comment]
@Keboo is this okay to merge? I reviewed the demo application and everything is working as before.

**Pull request merged**
