### PR TITLE
Fix mah apps integration

### LINKED ISSUE #1349: Some controls in MahApps Demo only show right color after palette change
The ToggleSwitch and the button on the "Mahapps" tab on the MahApps demo currently don't have the right theme after starting the app. Only after changing it in the plaette theme they have the right theme.

### PR DESCRIPTION
**Pull request by Keboo**
Work on getting MahApp functioning with the 3.0.0 stuff.

Renamed data grid text column to match the renaming of the combo box column.
Updated MahApps demo application with data grid styles.

Fixes #1349

### CODE REVIEW

**Comment by Mrxx99** [comment]
I guess this now fixes #1314?

**Comment by Mrxx99** [comment]
I guess this now fixes #1314?

**Comment by Keboo** [comment]
@Mrxx99 yea it gets pretty close. I did not want to close it yet as I suspect there might still be other issues to deal with. I did this work on my [live stream](https://www.youtube.com/watch?v=u2jK6vk6nsI) if anyone is interested in it.

**Comment by ahmediddma** [comment]
replace `BasedOn="{StaticResource MahApps.Metro.Styles.Slider.Thumb}"` with 
`BasedOn="{StaticResource MahApps.Styles.Thumb.Slider}"`

and `BasedOn="{StaticResource MahApps.Metro.Styles.RangeSlider.HorizontalMiddleThumb}"` with 
`BasedOn="{StaticResource MahApps.Styles.MetroThumb.RangeSlider.HorizontalMiddleThumb}"`

and `BasedOn="{StaticResource MahApps.Metro.Styles.Slider.HorizontalTrack}"` with 
`BasedOn="{StaticResource MahApps.Styles.RepeatButton.Slider.HorizontalTrack}"`

in file `MaterialDesignTheme.MahApps.RangeSlider.xaml`

for the sliders to work again

**Pull request merged**
