### PR TITLE
Support use of ColorZoneAssist in ComboBox

### PR DESCRIPTION
**Pull request by NZSmartie**
First part is addressing #679. Only when the ComboBox displays it's pop-over will the ColorZone take effect.
This does not change the border away from the primary mid brush.

Things to do:

- [X] Set the background and foreground when the popover is open.
- [x] Add a property for setting the border colour
- [x] ~~Copy changes over to UWP and adjust accordingly.~~

Please note that I'm still learning WPF and may not have taken the best approach for solving the issue.

### CODE REVIEW

**Comment by NZSmartie** [comment]
Preview of what I've got so far

**Comment by Keboo** [comment]
@NZSmartie I would not worry about doing anything for UWP. Right now it is not supported by this library.

**Comment by NZSmartie** [comment]
Added a new attached property `TextFieldAssistant.UnderlineBrush` which ideally is assigned to the Underline control's background property.

**Comment by NZSmartie** [comment]
there is a vertical bar visible when the drop down is open. Gonna address that next.

**Comment by NZSmartie** [comment]
Any feedback @ButchersBoy? should I continue working out the visual glitches? or not worth doing this PR?

**Comment by jespersh** [comment]
I noticed the vertical bar when I tested this on one of my monitors, but it didn't appear when I used the other.
Will have to check up if it was the primary or the secondary it was visible on, but it was enough to just drag it over for it to appear and disappear

**Comment by Keboo** [comment]
Rebased and updated the code with the latest library changes. In the demo app with the inverted combo box you will notice the background is transparent because of the theme brush. Not currently sure how to handle this case.

**Comment by Keboo** [comment]
Fixed the transparent popup background.

**Comment by ahmedflix25** [comment]
@Keboo what about using ColorZoneAssist with buttons, textboxes and labels it will make it easier to change their colors?

**Comment by Keboo** [comment]
@ahmedflix25 That is an interesting idea. I am not opposed to it, as it might make finding alternate color styles. I would probably want to rename it so it wasn't ColorZone specific. I will have to think about the relationship between such an attached property and the various styles that we have.

**Pull request merged**
