### PR TITLE
removed repeat buttons from scrollbar for a more minimalistic style

### PR DESCRIPTION
**Pull request by Insire**
Read through #646 and figured i give you something to play with.

Is this something you'd like to pursue, or does this not quite hit the spot? @ButchersBoy

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Personally, I like where this is going, but would prefer if it was slightly thinner.

**Comment by Insire** [comment]
The style uses the default windows size for scrollbars. I feel the same though. Making the scrollbar thinner would improve the look and feel.

**Comment by metherul** [comment]
I gotta agree, this looks really good.

**Comment by uPloraX** [comment]
Maybe I would add a bit of border radius to both ends too, otherwise it looks more like Metro and not in place when Material Design has these slightly details at whole.

**Comment by maciz84** [comment]
@Insire Do you have the style template for this scrollbar for sharing by any chance?

**Comment by maciz84** [comment]
@Insire oops my bad found it....I am fairly new to Github :)

**Comment by Keboo** [comment]
Putting this in the 2.6.0 release as I would like to see this issue revisited and brought forward.

**Comment by jespersh** [comment]
Would it be possible to add a property that shows/hides the RepeatButtons? Outright removing them seems a little too much, at least to me :-)

**Comment by Keboo** [comment]
Thank you for this work. I referenced it while getting the current styles in and done. See the work on PR #1270. Let me know if there is anything I have missed.

**Pull request closed without merging**
