### PR TITLE
NumericUpDown control support decimals value, and the value for each increase or decrease can be set.

### PR DESCRIPTION
**Pull request by futuresBoy**
NumericUpDown control support int and decimals value, and the value for each increase or decrease can be set.

### CODE REVIEW

**Comment by Keboo** [comment]
I am hesitant to change all of the types from `int` to `decimal` as that would be a breaking change for everyone currently using it.

I would propose the following alternate solution:
1. Create a new abstract `UpDownBase<T>` class. Most of the code could move into this base class with abstract members where needed.
2. Create a new DependencyProperty for `ValueStep` to represent the amount to be incremented or decremented.
3. Make the `NumericUpDown` derive from `UpDownBase<int>`
4. Create a new `DecimalUpDown` class and derive from `UpDownBase<decimal>`
5. Create a new implicit style for `DecimalUpDown` and have it based on the NumericUpDown style.

Thoughts?

**Comment by futuresBoy** [comment]
I got your proposal. I will create a new DecimalUpDown base on NumericUpDown

**Comment by futuresBoy** [comment]
Follow your proposal, I made the following changes:
1. Create a new abstract `UpDownBase<T>` class. 'NumericUpDown ' code move into this base class.
2. Besides, need define an interface 'IArithmetic ' to abstract the operation of the T-value between int and decimal and other Type.
3. Create a new DependencyProperty for `ValueStep` to represent the amount to be incremented or decremented.
4. Make the `NumericUpDown` derive from `UpDownBase<int>` and 'IArithmetic<int>'
5. Create a new `DecimalUpDown` class and derive from `UpDownBase<decimal>` and 'IArithmetic<int>'
6. Change TargetType 'NumericUpDown'  to 'UpDownBase', so the 'NumericUpDown ' and 'DecimalUpDown ' share the same style.

And in this way, it does't affect everyone who are using 'NumericUpDown' currently.

**Comment by Keboo** [comment]
@futuresBoy this is great work. I spent some time on my like stream doing some updates to leverage the new generic math on .NET8. 

There is an issue with my testing library (XAMLTest) that I want to address then we can get this merged.

**Review by Keboo — APPROVED** [review]

**Pull request merged**
